version: '3.3'

services:
  bot:
    image: "tg_bot"
    container_name: "tg_bot"
    stop_signal: SIGINT
    working_dir: "/usr/src/bot"
    volumes:
      - .:/usr/src/bot
    build:
      context: .
    command: "bash docker-entrypoint.sh"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ".env"

  # frontend:
  #   image: "webapp_frontend"
  #   container_name: "webapp_frontend"
  #   stop_signal: SIGINT
  #   build:
  #     context: ./webapp_frontend
  #     dockerfile: Dockerfile
  #   working_dir: "/usr/src/frontend"
  #   volumes:
  #     - ./webapp_frontend:/usr/src/frontend
  #   command: [ "npm", "deploy"]
  #   restart: always
  #   env_file:
  #     - ".env"

  # scheduler:
  #   image: "scheduler"
  #   container_name: "selflove_scheduler"
  #   stop_signal: SIGINT
  #   build:
  #     context: ./scheduler
  #     dockerfile: Dockerfile
  #   working_dir: "/usr/src/scheduler"
  #   volumes:
  #     - ./scheduler:/usr/src/scheduler
  #     - ./infrastructure:/usr/src/infrastructure
  #     - ./tgbot:/usr/src/tgbot
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   command: [ "python3", "main.py"]
  #   restart: always
  #   env_file:
  #     - ".env"

  backend:
    image: "backend"
    container_name: "webapp_backend"
    stop_signal: SIGINT
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: "/usr/src/backend"
    volumes:
      - ./webapp_backend:/usr/src/backend
    command: [ "fastapi run", "webapp", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    env_file:
      - ".env"

  


  nginx:
    container_name: webapp_nginx
    stop_signal: SIGINT
    restart: always
    image: nginx:latest
    ports:
      - "8088:8088"
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend